#! /bin/bash

set -x 

function 01tetragon() {
    echo "Starting tetragon"
    sudo ./tetragon --bpf-lib bpf/objs
}

function 02solar() {
    echo "Starting solarsploit exploit"
    sudo ./solarsploit
}

function 03build() {
    echo "Building with witness and BPF"
    ./witness run -l=debug --step build -o test-att.json --tetragon-address localhost:54321 -k demo-key.pem -- go build .
}

function 04show() {
    echo "Showing the attestation"
    cat test-att.json | jq -r .payload | base64 -d | jq -r '.predicate.attestations[] | select(.type=="https://witness.dev/attestations/command-run/v0.2") | .attestation.files["/home/cole/demo/witness-bpf-demo/main.go"]'
}


#if args is "1" then run 01tetragon
if [ "$1" = "1" ]; then
    echo "Running tetragon"
    01tetragon
fi

#if args is "2" then run 02solar
if [ "$1" = "2" ]; then
    echo "Running solarsploit"
    02solar
fi

#if args is "3" then run 03build
if [ "$1" = "3" ]; then
    echo "Running build"
    03build
fi

#if args is "4" then run 04show
if [ "$1" = "4" ]; then
    echo "Running show"
    04show
fi




# cat test-att.json | jq -r .payload | base64 -d | jq -r '.predicate.attestations[] | select(.type=="https://witness.dev/attestations/command-run/v0.2") | .attestation.files["/home/cole/demo/witness-bpf-demo/main.go"]'
# #/home/cole/demo/witness-bpf-demo/main.go
# ##Stop solarsploit
# sudo killall solarsploit


# ##Stop tetragon
# sudo killall tetragon










